alert("WELCOME TO FRESH BREADS,CAKES AND PASTRIES")
var visitorName = prompt("WELCOME TO FRESH BREADS,CAKES AND PASTRIES.WHAT IS YOUR NAME : ")
var TypeOfBread = prompt("KINDLY INPUT THE TYPE OF PASTRY YOU WANT AS SEEN ON THE SITE : ")
var REQUEST = confirm("YOUR PREFFERED PASTRY HAS BEEN REQUESTED.ARE YOU OKAY WITH WHAT YOU REQUESTED FOR?")
var APPROVAL = prompt("YOUR REQUEST HAS BEEN APPROVED.KINDLY INPUT YOUR DELIVERY DETAILS: ")
alert("YOUR DELIVERY WILL BE AT YOUR DOORSTEP AS SOON AS POSSIBLE.THANK YOU FOR TRUSTING US")

